import type { SiteData } from "@/lib/types";

const now = "2026-08-25T00:00:00.000Z";

export const fallbackData: SiteData = {
  photographs: [],
  events: [],
  settings: {
    id: "main",
    logo_url: null,
    hero_video_url: null,
    hero_mux_upload_id: null,
    hero_mux_asset_id: null,
    hero_mux_playback_id: null,
    hero_mux_status: null,
    hero_poster_url: null,
    showreel_url: null,
    about_image_url: null,
    team_image_url: null,
    cta_background_url: null,
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? "",
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL ?? "",
    email: "contato@aadesignmedia.com.br",
    address: "São Paulo, SP",
    hero_title: "CRIAMOS EXPERIÊNCIAS. CONTAMOS HISTÓRIAS.",
    hero_support: "DO SEU IDEAL AO RESULTADO EXTRAORDINÁRIO.",
    hero_description:
      "Produção audiovisual, fotografia e conteúdo para marcas que querem ser vistas, lembradas e sentidas.",
    about_text:
      "Arthur e Alana conduzem a AA Design & Media do briefing à entrega, combinando direção, captação e pós-produção em uma operação próxima, cuidadosa e feita sob medida para cada projeto.",
    footer_text: "Produção audiovisual, fotografia, drone e conteúdo em São Paulo."
  },
  projects: [
    {
      id: "terra-brasa",
      slug: "terra-brasa-conteudo-gastronomico",
      title: "Conteúdo gastronômico",
      client: "Terra Brasa",
      category: "Gastronomia",
      year: 2026,
      format: "Reels, fotografia e social content",
      description: "Captação recorrente de pratos, movimento da casa e rotina do restaurante.",
      full_description: null,
      services: ["Direção", "Captação", "Fotografia", "Edição"],
      credits: null,
      cover_url: null,
      video_url: null,
      mux_upload_id: null,
      mux_asset_id: null,
      mux_playback_id: null,
      mux_status: null,
      orientation: "vertical",
      aspect_ratio: "4/5",
      focal_x: 50,
      focal_y: 50,
      featured: true,
      published: true,
      position: 0,
      created_at: now,
      updated_at: now,
      project_media: []
    },
    {
      id: "jockey",
      slug: "jockey-club-turfe-em-movimento",
      title: "Turfe em movimento",
      client: "Jockey Club de São Paulo",
      category: "Esportes e turfe",
      year: 2026,
      format: "Vídeos e documentário",
      description: "Conteúdo sobre a rotina, as pessoas e a energia do turfe em São Paulo.",
      full_description: null,
      services: ["Roteiro", "Captação", "Entrevistas", "Pós-produção"],
      credits: null,
      cover_url: null,
      video_url: null,
      mux_upload_id: null,
      mux_asset_id: null,
      mux_playback_id: null,
      mux_status: null,
      orientation: "horizontal",
      aspect_ratio: "16/9",
      focal_x: 50,
      focal_y: 50,
      featured: true,
      published: true,
      position: 1,
      created_at: now,
      updated_at: now,
      project_media: []
    },
    {
      id: "donia",
      slug: "clinica-donia-social-content",
      title: "Imagem, cuidado e presença",
      client: "Clínica Donia",
      category: "Social Content",
      year: 2026,
      format: "Reels, fotografia e peças digitais",
      description: "Produção de conteúdo para apresentar procedimentos, equipe e experiência da clínica.",
      full_description: null,
      services: ["Planejamento", "Captação", "Fotografia", "Edição"],
      credits: null,
      cover_url: null,
      video_url: null,
      mux_upload_id: null,
      mux_asset_id: null,
      mux_playback_id: null,
      mux_status: null,
      orientation: "vertical",
      aspect_ratio: "4/5",
      focal_x: 50,
      focal_y: 50,
      featured: false,
      published: true,
      position: 2,
      created_at: now,
      updated_at: now,
      project_media: []
    },
    {
      id: "house-requinte",
      slug: "house-requinte-interiores",
      title: "Interiores em filme",
      client: "House Requinte",
      category: "Imóveis",
      year: 2026,
      format: "Vídeo, fotografia e social content",
      description: "Registro de ambientes planejados, detalhes de acabamento e obras concluídas.",
      full_description: null,
      services: ["Direção de fotografia", "Captação", "Edição"],
      credits: null,
      cover_url: null,
      video_url: null,
      mux_upload_id: null,
      mux_asset_id: null,
      mux_playback_id: null,
      mux_status: null,
      orientation: "horizontal",
      aspect_ratio: "16/10",
      focal_x: 50,
      focal_y: 50,
      featured: false,
      published: true,
      position: 3,
      created_at: now,
      updated_at: now,
      project_media: []
    },
    {
      id: "jm-fibra",
      slug: "jm-fibra-institucional",
      title: "Filme institucional",
      client: "JM Fibra",
      category: "Institucional",
      year: 2026,
      format: "Filme e fotografia",
      description: "Produção institucional com versões curtas e banco de imagens fotográficas.",
      full_description: null,
      services: ["Roteiro", "Drone", "Captação", "Pós-produção"],
      credits: null,
      cover_url: null,
      video_url: null,
      mux_upload_id: null,
      mux_asset_id: null,
      mux_playback_id: null,
      mux_status: null,
      orientation: "horizontal",
      aspect_ratio: "16/9",
      focal_x: 50,
      focal_y: 50,
      featured: false,
      published: true,
      position: 4,
      created_at: now,
      updated_at: now,
      project_media: []
    }
  ],
  services: [
    { id: "s1", title: "Produção audiovisual", description: "Projetos completos, do conceito à entrega final.", icon: "Clapperboard", visible: true, position: 0 },
    { id: "s2", title: "Vídeos institucionais", description: "Filmes que traduzem cultura, operação e propósito.", icon: "Building2", visible: true, position: 1 },
    { id: "s3", title: "Social Content e Reels", description: "Conteúdo nativo para Instagram, TikTok e YouTube.", icon: "Smartphone", visible: true, position: 2 },
    { id: "s4", title: "Fotografia profissional", description: "Campanhas, produtos, eventos e retratos com direção.", icon: "Camera", visible: true, position: 3 },
    { id: "s5", title: "Drone e FPV", description: "Imagens aéreas e movimentos imersivos para ampliar a narrativa.", icon: "Plane", visible: true, position: 4 },
    { id: "s6", title: "Cobertura de eventos", description: "Foto, vídeo, bastidores e entregas ágeis para o digital.", icon: "CalendarRange", visible: true, position: 5 },
    { id: "s7", title: "Documentários", description: "Histórias conduzidas com escuta, pesquisa e linguagem cinematográfica.", icon: "Film", visible: true, position: 6 },
    { id: "s8", title: "Pós-produção", description: "Edição, cor, tratamento de áudio e finalização multiformato.", icon: "SlidersHorizontal", visible: true, position: 7 }
  ],
  equipment: [
    { id: "e1", title: "Sony FX30", description: "Cinema digital 4K 10-bit para captação principal.", image_url: null, visible: true, position: 0 },
    { id: "e2", title: "Tamron 17–70mm f/2.8", description: "Versatilidade e consistência para produções em movimento.", image_url: null, visible: true, position: 1 },
    { id: "e3", title: "DJI Avata 360", description: "Perspectivas FPV e movimentos aéreos imersivos.", image_url: null, visible: true, position: 2 },
    { id: "e4", title: "Luz, áudio e estabilização", description: "Kit de produção adaptado a entrevistas, eventos e set.", image_url: null, visible: true, position: 3 }
  ],
  clients: [
    { id: "c1", name: "Terra Brasa", logo_url: null, visible: true, position: 0 },
    { id: "c2", name: "Jockey Club de São Paulo", logo_url: null, visible: true, position: 1 },
    { id: "c3", name: "Clínica Donia", logo_url: null, visible: true, position: 2 },
    { id: "c4", name: "House Requinte", logo_url: null, visible: true, position: 3 },
    { id: "c5", name: "JM Fibra", logo_url: null, visible: true, position: 4 }
  ],
  testimonials: [],
  behindScenes: [
    { id: "b1", title: "Captação em campo", media_url: null, poster_url: null, media_type: "video", equipment: "Sony FX30", orientation: "vertical", visible: true, position: 0 },
    { id: "b2", title: "Perspectiva aérea", media_url: null, poster_url: null, media_type: "video", equipment: "DJI Avata 360", orientation: "vertical", visible: true, position: 1 },
    { id: "b3", title: "Direção e luz", media_url: null, poster_url: null, media_type: "image", equipment: "Kit de iluminação", orientation: "vertical", visible: true, position: 2 }
  ]
};
